project:
  type: book

engine: knitr
book:
  title: "Regression Analysis With R and Easystats"
  author:
  - name: Maulik Bhatt
    email: maulik.bhatt@gmail.com
    affiliations:
      - name: S P Jain Institute of Management & Research
        address: Andheri
        city: Mumbai
        state: Maharashtra
  date: today
  date-format: DD/MM/YYYY
  #cover-image: cover.jpeg
  chapters:
    - index.qmd
    - introduction.qmd
    - econometrics.qmd
    - Getting_Started.qmd
    - lm.qmd
    - Multiple_Regression.qmd
    - Dummy_Variables.qmd
    - Heteroskedasticity.qmd
    - Time_Series.qmd
    - Logistic_Regression.qmd
    - Evaluation.qmd
    - Practical_Tips.qmd
    - Conclusion.qmd
  appendices:
    - Packages.qmd
    - Datasets.qmd
    - Code_Snippets.qmd
crossref:
  chapters: true
  appendix-title: "Appendix"

  

#bibliography: references.bib
format:
  html:
    theme: cosmo
  pdf:
    number-sections: true
    number-depth: 3
    documentclass: scrbook
    classoption: ["paper =a4", "twoside", "openright", "headsepline", "footsepline", "listof = totocnumbered", "chapterprefix = true", "firstiscover"]
    include-in-header:
      - file: preamble.tex
    margin-left: 1in
    margin-right: 1in
    margin-top: 1in
    margin-bottom: 1in
    colorlinks: true
    toc: true
    toc-title: "Contents"
    lot: true
    lof: true
    fig-cap-location: bottom
    fig-align: center
    fig-width: 6.5
    tbl-cap-location: top
    code-line-numbers: true
    keep-tex: true
    author-meta: "Maulik Bhatt"
    title-meta: "Regression Analysis With R and Easystats"
    hyperrefoptions:
    - linktoc=all
    - pdfwindowui
    - pdfpagemode=FullScreen
execute: 
  echo: true
  warning: false
  message: false
  error: false
  cache: true
editor: visual



