% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode,linktoc=all,pdfwindowui,pdfpagemode=FullScreen}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  paper =a4,
  twoside,
  openright,
  headsepline,
  footsepline,
  listof = totocnumbered,
  chapterprefix = true,
  firstiscover]{scrbook}

\usepackage{amsmath,amssymb}
\usepackage{setspace}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=1in,bottom=1in,left=1in,right=1in,heightrounded]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{3}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage[automark]{scrlayer-scrpage}%for header and footer
\pagestyle{scrheadings}
\usepackage{pagecolor}%to change the page color of the title page
\usepackage{setspace}%for line spacing
%\doublespacing

\providecommand{\abstractname}{Learning Objectives} % not in scrbook class
\newenvironment{objectives}[1]{%
	\hrule
	\vspace{5pt}
	\small\textbf{\abstractname: } 
	\newline
	\vspace{0.1cm}
	%\small\emph #1     %  emph takes an argument
	\small\emph{#1} % or \small\textit{#1} 
	\itshape % use this if you want the text to be in italics
}{%
	\vspace{5pt}
	\hrule
	\vspace{0.6cm}
}
%Quarto uses \maketitle command by default.
%So, if you want to add your custom title, you will have to
%redefine the command using the \renewcommand.
\definecolor{myblue}{RGB}{70, 130, 180}%steelblue color
\renewcommand{\maketitle}{
\begin{titlepage}
		\pagecolor{myblue}
		\color{white}
	\centering
	\vspace*{\baselineskip}
	\rule{\textwidth}{1.6pt}\vspace*{-\baselineskip}\vspace*{2pt}
	\rule{\textwidth}{0.4pt}\\[\baselineskip]
	{\LARGE Regression Analysis\\ With \\[0.3\baselineskip] R And Easystats}\\[0.2\baselineskip]
	\rule{\textwidth}{0.4pt}\vspace*{-\baselineskip}\vspace{3.2pt}
	\rule{\textwidth}{1.6pt}\\[\baselineskip]
	\scshape
	\vspace*{8\baselineskip}
	Author \\[\baselineskip]
	{\Large Maulik Bhatt \par}
	{\itshape S P Jain Institute of Management \& Research \\ Mumbai\par}
	\vfill
	{\scshape 2024} \\
	{\large Maulik Bhatt}\par%

\end{titlepage}
\nopagecolor%to change the page color of the subsequent pages
\newpage
	
	\thispagestyle{empty}
	
	\begin{center}
		
		Copyright © 2024 Maulik Bhatt
		
	\end{center}
	\newpage
}
%\uppertitleback{\copyright Maulik Bhatt}
%redesign chapter and section styles
\definecolor{mybluei}{RGB}{28,138,207}
\definecolor{myblueii}{RGB}{131,197,231}

\addtokomafont{disposition}{\usefont{T1}{qhv}{b}{n}\selectfont\color{myblueii}}

\addtokomafont{chapter}{\fontsize{30pt}{30pt}\selectfont}
\newkomafont{chapternumber}{\fontsize{50}{120}\selectfont\color{white}}
\newkomafont{chaptername}{\itshape\rmfamily\small\color{white}}

\addtokomafont{section}{\fontsize{14pt}{14pt}\selectfont}
\newkomafont{sectionnumber}{\fontsize{18pt}{18pt}\selectfont\rmfamily\color{white}}

\addtokomafont{subsection}{\fontsize{12pt}{12pt}\selectfont}
\newkomafont{subsectionnumber}{\fontsize{16pt}{16pt}\selectfont\rmfamily\color{white}}

\renewcommand\chapterformat{%
  \raisebox{-6pt}{\colorbox{mybluei}{%
    \parbox[b][60pt]{45pt}{\centering%
      {\usekomafont{chaptername}{\chapapp}}%
      \vfill{\usekomafont{chapternumber}{\thechapter}}%
      %\vfill{\usekomafont{chapternumber}{\thechapter\autodot}}%
      \vspace{6pt}%
}}}\enskip}

\renewcommand\sectionformat{%
  \setlength\fboxsep{5pt}%
  \raisebox{-4pt}{\colorbox{mybluei}{%
    \enskip\usekomafont{sectionnumber}{\thesection}\enskip}%
    %\enskip\usekomafont{sectionnumber}{\thesection\autodot}\enskip}%
  \quad%
}}

\renewcommand\subsectionformat{%
  \setlength\fboxsep{5pt}%
  \raisebox{-4pt}{\colorbox{mybluei}{%
    \enskip\usekomafont{subsectionnumber}{\thesubsection\autodot}\enskip}%
  \quad%
}}

\makeatletter
\renewcommand\sectionlinesformat[4]{%
  \makebox[0pt][l]{\rule[-5pt]{\textwidth}{1pt}}%
  \@hangfrom{#3}{#4}%
}
\makeatother
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}{}
\makeatother
\makeatletter
\@ifundefined{codebgcolor}{\definecolor{codebgcolor}{HTML}{EFEFEF}}{}
\makeatother
\makeatletter
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[sharp corners, enhanced, boxrule=0pt, frame hidden, colback={codebgcolor}, breakable]}{\end{tcolorbox}}\fi
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Regression Analysis With R and Easystats},
  pdfauthor={Maulik Bhatt},
  colorlinks=true,
  linkcolor={Maroon},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Regression Analysis With R and Easystats}
\author{Maulik Bhatt}
\date{10/06/2024}

\begin{document}
\frontmatter
\maketitle

\renewcommand*\contentsname{Contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}
\listoffigures
\listoftables
\setstretch{2}
\mainmatter
\bookmarksetup{startatroot}

\chapter*{Preface}\label{preface}
\addcontentsline{toc}{chapter}{Preface}

\markboth{Preface}{Preface}

\bookmarksetup{startatroot}

\chapter*{Acknowledgement}\label{acknowledgement}
\addcontentsline{toc}{chapter}{Acknowledgement}

\markboth{Acknowledgement}{Acknowledgement}

I would like to express my heartfelt gratitude to the individuals who
have played a significant role in the creation of this book on
Regression Analysis with R. Their guidance, knowledge, and support have
been invaluable throughout this journey.

First and foremost, I extend my deepest appreciation to my esteemed
professors, {[}Professor's Name{]}, {[}Professor's Name{]}, and
{[}Professor's Name{]}. Their expertise in statistics and econometrics
has shaped my understanding of quantitative analysis and provided a
solid foundation for this book. Their dedication to teaching and their
unwavering commitment to fostering academic excellence have been
instrumental in my growth as a student of econometrics.

I would like to extend special thanks to my colleague and dear friend,
{[}Colleague's Name{]}. Their introduction to the world of R programming
language opened up a world of possibilities for me. Their patience,
willingness to share their knowledge, and countless hours spent
assisting me with R-related challenges have been indispensable. I am
grateful for their unwavering support and the collaborative environment
we fostered, which significantly enriched my learning experience.

A heartfelt appreciation goes to the developers of R, an open-source
programming language that has revolutionized the field of data analysis
and statistical computing. Their tireless efforts in creating and
continuously improving R have made it an indispensable tool for
researchers and analysts worldwide. Without their dedication, this book
would not have been possible.

I would also like to express my gratitude to the developers of the R
packages that have been instrumental in the analysis and visualization
techniques presented in this book. Their commitment to excellence,
innovation, and user-friendly implementations has immensely contributed
to the field of regression analysis. Their packages have not only
expanded the capabilities of R but have also facilitated the seamless
integration of econometric methodologies into practical applications.

Finally, I extend my heartfelt thanks to my family and friends who have
supported me throughout this writing process. Their encouragement,
understanding, and belief in my abilities have been a constant source of
motivation.

To all those mentioned above, and to anyone else who has contributed to
this book in any way, I offer my deepest appreciation. Your guidance,
knowledge, and support have been invaluable in shaping this work and
have helped me fulfill my goal of sharing the beauty and importance of
regression analysis with R.

Thank you.

{[}Your Name{]}

\bookmarksetup{startatroot}

\chapter{Introduction}\label{introduction}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Importance of regression analysis in econometrics}

\item{Overview of the book's structure and goals}

\item{Introduction to R programming language and its relevance to econometric analysis}

\end{itemize}

\end{objectives}

Econometrics is a combination of two words: Econo + Metric. Econo refers
to concepts of economics, while metric refers to measurement. Let's take
an example of the law of demand from microeconomic theory. We know the
demand of a commodity will decrease if the price of the commodity
increases. But we don't know how much the demand will decrease, given
the increase in the price is one unit (i.e., one Dollar, or one Euro,
etc.). In Econometrics, we measure such increase or decrease using
various experiments. In these experiments, we observe how much the
demand for a commodity increase of decrease in response to a unit change
(increase or decrease) in price of the commodity.

\section{Importance of R for Econometrics and
Statistics}\label{importance-of-r-for-econometrics-and-statistics}

Many software are available for statistical and econometric analysis.
Some of the popular software include SPSS, SAS, Stata, MATLAB, etc.
These are all proprietary software. Free and open source alternatives
include python and R, which are programming languages. The users need to
type the commands in order to perform various tasks/analysis in these
programming languages.

Python is a general purpose programming langauge, while R is a
statistical programming language. R also has many packages (i.e.,
add-ons, which enhance the functionality of R). As of writing this,
there are \texttt{19697} packages available on CRAN (the Comprehensive R
Archive Network, which is the central authority to decide about R
programming language). Even more packages are available on
\texttt{github}, which is an Internet hosting service for software
development and version control using the version control system Git.
Because of such extensive support, I have chosen R to conduct
econometric analysis for this book.

In particular, I will use \texttt{easystats} set of packages, which are
designed for various statistical analysis tasks. We will see how
\texttt{easystats} make our tasks easier in R.

I will also use \texttt{quarto}, which is a document preparation system,
based on pandoc's markdown. The benefit of \texttt{quarto} is that we
can keep our analysis and prose in the same document. At the end, when
we click on the \texttt{build} button, it renders the entire book in
either pdf or HTML format. It is also possible to render the book in
Microsoft Word format, but this output format has got limited support.
It is more convenient to design and customize the output in HTML and PDF
formats. We will discuss more about this in the chapter of Getting
Started with R.

\bookmarksetup{startatroot}

\chapter{Introduction to Econometrics and Regression
Analysis}\label{introduction-to-econometrics-and-regression-analysis}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Understanding the basics of econometrics}

\item{Role of regression analysis in econometric modeling}

\item{Overview of the regression analysis process}

\item{Introduction to R for econometric analysis}

\end{itemize}

\end{objectives}

Basics of Econometrics

Role of Regression

Introduction to R

Imagine economics as a world of ideas. Economists come up with theories
that explain how the economy works, like how changes in price affect
demand. These theories are great for understanding the general
principles, but they often lack specifics. They can't tell you exactly
how much demand will drop if the price goes up by a certain amount.

That's where econometrics comes in. It acts as a bridge between these
economic theories and the messy, real world. The word ``econometrics''
is made of two words: Economics, and Metrics. Metrics means measurement.
Thus, econometrics means introducing measurement inside economics.
Econometrics uses tools from statistics and math to turn those economic
theories into something measurable. Here's the breakdown:

\begin{itemize}
\item
  \textbf{Quantify relationships:} Econometrics doesn't just say
  ``demand goes down with price increase,'' it can tell you by how much.
  It uses statistical methods like regression analysis to find the exact
  mathematical relationship between price and demand based on real-world
  data.
\item
  \textbf{Test theories:} Economic theories are like educated guesses.
  Econometrics allows us to test those guesses with real data. Using
  statistical tests, econometricians can see if the data actually
  supports the theory or not. Maybe higher prices don't always decrease
  demand as much as the theory predicted.
\item
  \textbf{Informed decisions:} By giving us numbers and concrete
  evidence, econometrics helps us make better decisions about the
  economy. Policymakers can use econometric models to see how changes in
  interest rates might affect inflation, or businesses can use them to
  predict how much demand there will be for their product if they raise
  the price.
\end{itemize}

This chapter is like a map to understanding econometrics. It will
introduce you to the core methods (like regression analysis) and show
you how they're used in different areas like business forecasting or
analyzing the labor market.

In short, econometrics takes economic theories from the world of ideas
and translates them into tools we can use to understand and navigate the
real economic world.

The Role of Econometrics in Economics

Economic theories often propose qualitative relationships between
variables. For instance, a theory might suggest that an increase in
income leads to a rise in consumption. Econometrics allows us to
quantify this relationship by estimating the magnitude of change in
consumption for a given change in income. This is achieved by
constructing mathematical models that represent the theoretical
relationships and then employing statistical techniques to estimate the
unknown parameters within these models.

\textbf{Economic Theories as Qualitative Descriptions:} Economic
theories provide valuable insights into how the economy functions.
However, these theories often describe relationships between variables
in qualitative terms. For example, a theory might simply state that
there's a positive relationship between income and consumption, but it
doesn't tell us by how much consumption increases for a specific
increase in income.

\textbf{Econometrics: Bridging the Gap with Quantification:} This is
where econometrics steps in. It acts as a bridge between these
qualitative theories and the quantitative world. Econometricians achieve
this by:

\begin{itemize}
\item
  \textbf{Mathematical Modeling:} They construct mathematical models
  that represent the theoretical relationships between variables. These
  models typically involve equations that express the dependent variable
  (e.g., consumption) as a function of the independent variable (e.g.,
  income) and potentially other relevant factors.
\item
  \textbf{Statistical Estimation:} The models contain unknown parameters
  that need to be estimated using real-world data. Econometricians
  employ various statistical techniques, like regression analysis, to
  estimate these parameters. This allows them to quantify the magnitude
  and direction of the relationship between the variables.
\end{itemize}

In essence, econometrics takes the qualitative predictions of economic
theories and transforms them into measurable and testable relationships.
By estimating the unknown parameters within the models, econometricians
can tell us not just that consumption goes up with income, but by
exactly how much it's expected to rise for a given increase in income.
This quantitative information proves invaluable for various
applications, such as economic forecasting, policy analysis, and
business decision-making.

\subsection{Econometric Methodology}\label{econometric-methodology}

The econometric toolbox is vast, but some fundamental methods include:

\begin{itemize}
\item
  \textbf{Regression Analysis:} This technique explores the relationship
  between a dependent variable (the variable being explained) and one or
  more independent variables (explanatory variables). By estimating the
  coefficients of the independent variables, we can quantify their
  impact on the dependent variable.
\item
  \textbf{Hypothesis Testing:} Econometrics allows us to statistically
  test economic hypotheses. This involves formulating a null hypothesis
  (typically, no relationship exists) and an alternative hypothesis (a
  specific relationship exists), and then using statistical tests to
  determine if the data supports rejecting the null hypothesis in favor
  of the alternative.
\item
  \textbf{Time Series Analysis:} This method deals with analyzing data
  collected over time, allowing us to understand trends, seasonality,
  and potential causal relationships between economic variables.
\end{itemize}

\subsection{Applications of
Econometrics}\label{applications-of-econometrics}

Econometrics has a wide range of applications in various economic
fields. Here are some prominent examples:

\begin{itemize}
\item
  \textbf{Demand Forecasting:} Businesses can utilize econometric models
  to forecast consumer demand for their products based on factors like
  income, price, and advertising expenditures.
\item
  \textbf{Monetary Policy Analysis:} Central banks employ econometric
  models to assess the impact of interest rate changes on inflation,
  unemployment, and economic growth.
\item
  \textbf{Labor Market Analysis:} Econometricians use these methods to
  examine the effects of minimum wage laws, training programs, and other
  policies on employment levels and wages.
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Getting Started with R for
Econometrics}\label{sec-getting-started}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Introduction to R programming language and its ecosystem}

\item{Setting up the R environment and installing necessary packages}

\item{Loading and manipulating data in R for econometric analysis}

\item{Exploring data visualization techniques using R}

\end{itemize}

\end{objectives}

\section{A Brief History of R}\label{a-brief-history-of-r}

John Chambers, working at Bell Laboratories, developed S programming
language for statistical analysis. This programming language was
incorporated in the commercial program S-plus. Inspired by this
programming languagage, tw o statistics professors Robert Gentleman and
Ross Ihaka developed a reduced version of S, which they named R.

R was first released in 1993. In 1995, another statistician Martin
Mächler convinced Gentleman and Ihaka to make R source code available to
general public. As a result, R became free and open source under GNU
General Public License.

R also has a robust community of users. As of writing this, there are
20607 user-developed packages on Comprehensive R Archive Network (CRAN),
which distributes the R source code and packages. Apart from CRAN, many
more packages are also available on code sharing platform github. Users
can download packages from github as well. The Appendix A explains how
to install packages from CRAN and from github.

\section{How to Install R}\label{how-to-install-r}

You can install R from the website of
\href{https://cran.r-project.org/}{CRAN}. Downloadable files and
instructions to download and install R for all the major operating
systems are available on this website. R can be downloaded and installed
on Windows, Mac and Linux platforms.

It is possible to use R right from within this R Graphical User
Interface (R-Gui). But such a work will not be reproducible. It means,
you will be able to work on your system, but you won't be able to share
that work with others. IDE like RStudio makes it much easier to work in
R, and to share your work with others.

\section{How to Install RStudio}\label{how-to-install-rstudio}

Once you have installed R for your operating system, you can visit the
website of \href{https://posit.co/download/rstudio-desktop/}{RStudio}.
Just like R, RStudio is also available on Windows, Mac and Linux
platforms.

\section{Useful Settings in RStudio}\label{useful-settings-in-rstudio}

I would recommend you not to save the workspace in RStudio. This setting
can be disabled in RStudio as follows:

\begin{figure}[h]

\centering{

\includegraphics[width=3.92in,height=\textheight]{images/RStudio-settings.png}

}

\caption{\label{fig-disable-workspace}How to Disable Saving Workspace}

\end{figure}%

This setting (of not saving your workspace) seems counter-intuitive. But
it helps you in the longer term. Assume you have to share your work with
someone else. The other person might not have the same settings of
computer in his/her system. So, the work on your system might look
different in that system. Instead, you should save the R Script (or even
better, a Quarto document) in your system, and should share it.

\section{The Concept of Working
Directory}\label{the-concept-of-working-directory}

R has a concept of working directory. When you save your R script and
your work, it gets saved in the ``working directory'' of R. You can find
and change the working directory using R commands.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Find the working directory}
\FunctionTok{getwd}\NormalTok{()}
\CommentTok{\#Change the working directory}
\CommentTok{\#setwd("Path/to/another/folder")}
\end{Highlighting}
\end{Shaded}

\section{Quarto}\label{quarto}

Quarto is a new open-source scientific and technical publishing system
developed by Posit (the maker of RStudio). Quarto is designed to be
useful to anyone who wants to create reproducible documents. A Quarto
document contains both - the code and the prose. For example, if you are
running regression analysis in R, R Script will only contain your code,
but a Quarto document will contain your R code and your interpretation
of the regression results. Quarto runs computations into separate
pluggable language ``engines'', which helps make this cross-language
functionality easier to support .

Here are some points that emphasize the reproducibility of Quarto over R
scripts:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Cross-language support}: Quarto is designed to work with
  multiple languages, including Python, bash, Julia, C, SQL, and more.
  This makes it easier to work with different languages in the same
  document.
\item
  \textbf{Built-in output formats}: Quarto generates the output in
  various formats like Microsoft Word, HTML, PDF, beamer, revealjs, etc.
  It also has many options for customizing each format.
\item
  \textbf{Native features for special project types}: Quarto has native
  features for special project types like websites, books, and blogs.
  This means that you don't have to rely on external packages. As a
  matter of fact, this book is written entirely using Quarto in RStudio.
\item
  \textbf{Easier rendering}: Quarto isn't an R package. It's a
  command-line interface that makes it much easier to work with Quarto
  documents outside of the RStudio IDE. You can also use Quarto in other
  IDEs like VS Code.
\end{enumerate}

These features make Quarto a better choice than R scripts when it comes
to reproducibility. With Quarto, you can easily create documents that
are easy to reproduce and share with others.

\section{\texorpdfstring{Optional: Installing
\LaTeX}{Optional: Installing }}\label{optional-installing}

If you want to work in Quarto, and want to generate PDF output,
\LaTeX is required. There are two popular \LaTeX distributions: MiKTeX
and TeX Live. However, I prefer another \LaTeX distribution, called
TinyTeX. It's a light weight distribution of \LaTeX, and works well with
R. You can install it using R as follows:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#install tinytex R package}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"tinytex"}\NormalTok{)}
\CommentTok{\#load it in R}
\FunctionTok{library}\NormalTok{(tinytex)}
\CommentTok{\#use this package to install LaTeX compiler TinyTeX}
\FunctionTok{install\_tinytex}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

These commands install the most commonly used \LaTeX packages into your
system. However, if you want to install all the \LaTeX packages, you can
do so by using \texttt{install\_tinytex(bundle\ =\ "TinyTeX-2")} instead
of \texttt{install\_tinytex()} function above.

\section{Your First Interaction with
R}\label{your-first-interaction-with-r}

After installing R and RStudio, you would start RStudio (not R). RStudio
has four parts in the screen. The four parts (called ``panes'') are
source pane, console pane, environment pane and files pane. You can
customize each pane using
\texttt{Tools\ Menu\ \textgreater{}\ Global\ Options\ \textgreater{}\ Pane\ Layout}.
The RStudio screen looks as follows:

\begin{figure}[h]

\centering{

\includegraphics[width=4.27in,height=\textheight]{images/RStudio-panes.png}

}

\caption{\label{fig-rstudio-panes}RStudio Panes}

\end{figure}%

When you open a new file in RStudio using the
\texttt{Files\ Menu\ \textgreater{}\ New\ File}, you are presented with
many options like R Script, R Markdown Document, Quarto Document, etc. I
would suggest you to choose R Markdown Document or Quarto Document,
because in these two file formats, you can write both - your analysis
and your prose. Your document will be saved in your working directory.

In RStudio's File Menu, you will also find another option:
\texttt{New\ Project}. This is a considerable improvement over a new
file - be it an R Script or a Quarto Document. This is because it
changes the working directory of the project to the folder, where
\texttt{.Rproj} file of the project is stored. You can share this folder
with anyone, and the code will work just fine on that computer also.

When you go to
\texttt{File\ Menu\ \textgreater{}\ New\ Project\ \textgreater{}\ New\ Directory},
you get options as follows:

\begin{figure}[h]

\centering{

\includegraphics[width=4.27in,height=\textheight]{images/New_Project.png}

}

\caption{\label{fig-rstudio-project}Types of RStudio Projects}

\end{figure}%

As you can see, it has many options like RStudio Project, R Package,
Quarto Project, Quarto Website, Quarto Blog and Quarto Book. This book
is written using a Quarto Book project.

\section{Installing Packages}\label{installing-packages}

You can install packages using the command
\texttt{install.packages(package\_name)}. For example, the command to
install the \texttt{easystats} set of packages would be
\texttt{install.packages(easystats)}.

\section{Loading and Manipulating
Data}\label{loading-and-manipulating-data}

In order to analyse the data, we need to load or import the data first.
There are many possibilities as far as loading/importing data is
concerned. If the data comes from a package, then you can directly load
the data using the \texttt{data(dataset\_name)} command. For example,
the command \texttt{data(mtcars)} will load the \texttt{mtcars} dataset
into the environment. This dataset comes in-built in R.

Most of the data comes from external sources in different file formats
like csv or Microsoft Excel. Data in csv file format can easily be read
using the \texttt{read.csv(path\_to\_data\_file)} command. There is
\texttt{readr} package also, which is part of the \texttt{tidyverse} set
of packages. This package \texttt{readr} can import csv data and load it
in the environment as a \texttt{tibble}. The native data format in R is
\texttt{data.frame}, and \texttt{tibble} is ``advanced version of
\texttt{data.frame} according to the developers of the tidyverse set of
packages.

Similarly, to import data from Microsoft Excel file, there is
\texttt{readxl} package, which is also a part of \texttt{tidyverse}.
Just like \texttt{readr}, \texttt{readxl} would also import the data in
form of a \texttt{tibble}. Both the packages also share similar
interface to import data.

The packages \texttt{foreign} and \texttt{haven} are useful for
importing data from other statistical packages like SPSS, SAS and STATA.

Another noteworthy package is \texttt{data.table}, which can import data
from many formats. Its function \texttt{fread} is versatile and can read
data in many formats.

\subsection{Manipulating Data}\label{manipulating-data}

Although R is capable of data manipulation without using any other
packages, some of the packages created especially to facilitate data
manipulation makes the process easy and understandable for others. In
our examples, we will use \texttt{tidyverse} set of packages for data
manipulation. In particular, two of its packages \texttt{dplyr} and
\texttt{tidyr} make this process quite easy.

\subsection{Selecting Columns from
Dataset}\label{selecting-columns-from-dataset}

We can use the \texttt{select} command from \texttt{dplyr} for selecting
columns from a dataset.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(conflicted)}
\FunctionTok{conflict\_prefer}\NormalTok{(}\StringTok{"lag"}\NormalTok{, }\StringTok{"dplyr"}\NormalTok{)}
\FunctionTok{conflict\_prefer}\NormalTok{(}\StringTok{"tidy"}\NormalTok{, }\StringTok{"broom"}\NormalTok{)}
\FunctionTok{conflict\_prefer}\NormalTok{(}\StringTok{"augment"}\NormalTok{,}\StringTok{"broom"}\NormalTok{)}
\NormalTok{mtcars }\SpecialCharTok{|\textgreater{}} \FunctionTok{select}\NormalTok{(am}\SpecialCharTok{:}\NormalTok{carb) }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{() }\SpecialCharTok{|\textgreater{}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrr@{}}
\caption{Selecting Columns from am to carb from mtcars
dataset}\tabularnewline
\toprule\noalign{}
& am & gear & carb \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& am & gear & carb \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Mazda RX4 & 1 & 4 & 4 \\
Mazda RX4 Wag & 1 & 4 & 4 \\
Datsun 710 & 1 & 4 & 1 \\
Hornet 4 Drive & 0 & 3 & 1 \\
Hornet Sportabout & 0 & 3 & 2 \\
Valiant & 0 & 3 & 1 \\
\end{longtable}

In the above command, we first loaded the \texttt{tidyverse} set of
packages, so that its functionality is available in the R session. Then
we took the built-in dataset \texttt{mtcars}, and then selected the
columns from \texttt{am} to \texttt{carb} in the dataset. The
\texttt{\textbar{}\textgreater{}} is called the \texttt{pipe\ operator}
in R. It was introduced in R version 4.1. Before that, there was another
pipe operator (\texttt{\%\textgreater{}\%}) in the \texttt{magrittr}
package, which is also a part of \texttt{tidyverse}. To understand how
pipe operator makes coding easy and readable, imagine you want to take
g(f(x)), which reads g of f of x. It means you want to take a value x,
apply the function f on that value, and on the output, you want to apply
another function g. Before the introduction of pipe operator, you would
have written it as \texttt{g(f(x))}, but now after R 4.1, you can write
it as
\texttt{x\ \textbar{}\textgreater{}\ f()\ \textbar{}\textgreater{}\ g()}.

\subsection{\texorpdfstring{Selecting Rows from a Dataset (aka
\texttt{filtering})}{Selecting Rows from a Dataset (aka filtering)}}\label{selecting-rows-from-a-dataset-aka-filtering}

We can use \texttt{filter} function from \texttt{dplyr} for filtering
rows of a dataset. For example, we want to filter the rows of
\texttt{mtcars} dataset, where \texttt{cyl} is equal to 6. We can do
this by

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars }\SpecialCharTok{|\textgreater{}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(cyl}\SpecialCharTok{==}\DecValTok{6}\NormalTok{) }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{() }\SpecialCharTok{|\textgreater{}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.2239}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0746}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0597}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0896}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0597}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0746}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0896}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0896}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0448}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0448}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0746}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0746}}@{}}
\caption{Selecting Rows from mtcars dataset where value of cyl is
6}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mpg
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
cyl
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
disp
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
hp
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
drat
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
wt
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
qsec
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
vs
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
am
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
gear
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
carb
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mpg
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
cyl
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
disp
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
hp
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
drat
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
wt
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
qsec
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
vs
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
am
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
gear
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
carb
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Mazda RX4 & 21.0 & 6 & 160.0 & 110 & 3.90 & 2.620 & 16.46 & 0 & 1 & 4 &
4 \\
Mazda RX4 Wag & 21.0 & 6 & 160.0 & 110 & 3.90 & 2.875 & 17.02 & 0 & 1 &
4 & 4 \\
Hornet 4 Drive & 21.4 & 6 & 258.0 & 110 & 3.08 & 3.215 & 19.44 & 1 & 0 &
3 & 1 \\
Valiant & 18.1 & 6 & 225.0 & 105 & 2.76 & 3.460 & 20.22 & 1 & 0 & 3 &
1 \\
Merc 280 & 19.2 & 6 & 167.6 & 123 & 3.92 & 3.440 & 18.30 & 1 & 0 & 4 &
4 \\
Merc 280C & 17.8 & 6 & 167.6 & 123 & 3.92 & 3.440 & 18.90 & 1 & 0 & 4 &
4 \\
\end{longtable}

We can see that in this code, we have used ``='' twice. In R, ``='' is
an assignment operator. It means, when we write \texttt{cyl=6}, it
assigns value 6 to the variable \texttt{cyl}. So, when we want to check
equality, we have to use ``=='' instead of ``=''.

\subsection{Arrange Data}\label{arrange-data}

Using \texttt{dplyr}, it is easy to arrange or sort data in ascending or
descending order of a column: use the \texttt{arrange} function for
that.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars }\SpecialCharTok{|\textgreater{}} \FunctionTok{arrange}\NormalTok{(mpg)}\SpecialCharTok{|\textgreater{}} \FunctionTok{select}\NormalTok{(mpg}\SpecialCharTok{:}\NormalTok{disp) }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{() }\SpecialCharTok{|\textgreater{}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrr@{}}
\caption{Arrange the Data in Ascending Order of
\texttt{mpg}}\tabularnewline
\toprule\noalign{}
& mpg & cyl & disp \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& mpg & cyl & disp \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Cadillac Fleetwood & 10.4 & 8 & 472 \\
Lincoln Continental & 10.4 & 8 & 460 \\
Camaro Z28 & 13.3 & 8 & 350 \\
Duster 360 & 14.3 & 8 & 360 \\
Chrysler Imperial & 14.7 & 8 & 440 \\
Maserati Bora & 15.0 & 8 & 301 \\
\end{longtable}

You can similarly arrange the data in descending order of \texttt{mpg}
column in the \texttt{mtcars} dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars }\SpecialCharTok{|\textgreater{}} \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(mpg)) }\SpecialCharTok{|\textgreater{}} \FunctionTok{select}\NormalTok{(mpg}\SpecialCharTok{:}\NormalTok{disp) }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{() }\SpecialCharTok{|\textgreater{}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrr@{}}
\caption{Arrange the Data in Descending Order of
\texttt{mpg}}\tabularnewline
\toprule\noalign{}
& mpg & cyl & disp \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& mpg & cyl & disp \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Toyota Corolla & 33.9 & 4 & 71.1 \\
Fiat 128 & 32.4 & 4 & 78.7 \\
Honda Civic & 30.4 & 4 & 75.7 \\
Lotus Europa & 30.4 & 4 & 95.1 \\
Fiat X1-9 & 27.3 & 4 & 79.0 \\
Porsche 914-2 & 26.0 & 4 & 120.3 \\
\end{longtable}

\subsection{Create a New Variable}\label{create-a-new-variable}

You can create a new variable using the \texttt{mutate} function in
\texttt{dplyr} package. For example, you want to create a new variable,
called FuelEff, which is defined as reciprocal of mpg, then you can do
it as follows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars }\SpecialCharTok{|\textgreater{}} \FunctionTok{mutate}\NormalTok{(}\AttributeTok{FuelEff =} \DecValTok{1}\SpecialCharTok{/}\NormalTok{mpg) }\SpecialCharTok{|\textgreater{}} \FunctionTok{select}\NormalTok{(am}\SpecialCharTok{:}\NormalTok{FuelEff) }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{() }\SpecialCharTok{|\textgreater{}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Create a New Variable in \texttt{mtcars}
dataset}\tabularnewline
\toprule\noalign{}
& am & gear & carb & FuelEff \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& am & gear & carb & FuelEff \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Mazda RX4 & 1 & 4 & 4 & 0.0476190 \\
Mazda RX4 Wag & 1 & 4 & 4 & 0.0476190 \\
Datsun 710 & 1 & 4 & 1 & 0.0438596 \\
Hornet 4 Drive & 0 & 3 & 1 & 0.0467290 \\
Hornet Sportabout & 0 & 3 & 2 & 0.0534759 \\
Valiant & 0 & 3 & 1 & 0.0552486 \\
\end{longtable}

\section{Summarize a Data}\label{summarize-a-data}

Suppose you want to see what is the average \texttt{mpg} in the whole
dataset? Remember mpg stands for miles per gallon. So, this column shows
the fuel efficiency of various cars. So, you can use \texttt{summary}
function from dplyr to get this answer.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars }\SpecialCharTok{|\textgreater{}} \FunctionTok{summarise}\NormalTok{(}\StringTok{"Average MPG"} \OtherTok{=} \FunctionTok{mean}\NormalTok{(mpg)) }\SpecialCharTok{|\textgreater{}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}r@{}}
\caption{Average Miles Per Gallon of Cars in USA}\tabularnewline
\toprule\noalign{}
Average MPG \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Average MPG \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
20.09062 \\
\end{longtable}

However, this function \texttt{summarise} becomes more powerful when
combined with another function \texttt{group\_by}. For example, you want
to know if there is difference in mean mpg for different level of cyl.
You can see it using the following code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars }\SpecialCharTok{|\textgreater{}} \FunctionTok{group\_by}\NormalTok{(cyl) }\SpecialCharTok{|\textgreater{}} \FunctionTok{summarise}\NormalTok{(}\StringTok{"Average MPG"} \OtherTok{=} \FunctionTok{mean}\NormalTok{(mpg)) }\SpecialCharTok{|\textgreater{}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rr@{}}
\caption{Miles Per Gallon for Different Values of
Cylinder}\tabularnewline
\toprule\noalign{}
cyl & Average MPG \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
cyl & Average MPG \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
4 & 26.66364 \\
6 & 19.74286 \\
8 & 15.10000 \\
\end{longtable}

The \texttt{group\_by} argument changes the unit of analysis. For
example, if we write the code
\texttt{mtcars\ \textbar{}\textgreater{}\ summarize(mean\_mpg\ =\ mean(mpg))},
then the unit of analysis is all the the observations of the
\texttt{mpg} column. But when we introduce \texttt{group\_by}, by
writing
\texttt{mtcars\ \textbar{}\textgreater{}\ group\_by(cyl)\ \textbar{}\textgreater{}\ summarise("Average\ MPG"\ =\ mean(mpg))},
then the unit of analysis is each level of \texttt{cyl} variable. Now
the average of \texttt{mpg} is calculated for each level of
\texttt{cyl}, instead of calculating it for the whole lot of
observation.

\bookmarksetup{startatroot}

\chapter{Simple Linear Regression}\label{simple-linear-regression}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Understanding the principles of simple linear regression}

\item{Performing simple linear regression in R for econometric analysis}

\item{Interpreting regression results in the context of economic variables}

\item{Assessing model assumptions and addressing violations}

\item{Practical examples and exercises using R}

\end{itemize}

\end{objectives}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(easystats)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\section{Introduction}\label{introduction-1}

Linear regression is among the fundamental concepts in Econometrics. In
linear regression, we try to estimate how much one variable will change,
with response to a change in another variable. The controlled variable
is called predictor or independent variable. The variable, which changes
as a response to a change in the controlled variable is called response
or dependent variable. In R, we denote such relationship with
\texttt{y\textasciitilde{}x}, where y is the response and x is the
predictor. The notation \texttt{y\textasciitilde{}x} is read as ``y
explained by x''.

In mathematical terms, we are fitting a linear equation between x and y.
When we write \texttt{y\textasciitilde{}x}, it means
\texttt{y\ =\ ax\ +\ b}, and we need to find a and b from the data
points given.

\section{Unveiling Relationships: The Purpose of Linear
Regression}\label{unveiling-relationships-the-purpose-of-linear-regression}

Linear regression, a cornerstone of statistical analysis, empowers us to
delve into the fascinating world of relationships between variables.
Imagine yourself as a data detective, piecing together clues to
understand how one element influences another. This is precisely the
role linear regression plays.

Suppose you're an enterprising researcher curious about the link between
study hours and exam scores. Linear regression offers a method to
uncover this connection. By harnessing the power of this technique, you
can not only \textbf{predict} potential exam scores based on the number
of hours a student studies, but also gain valuable insights into the
\textbf{strength} of this relationship.

Consider the following scenario: you establish a model depicting the
relationship between study hours and exam scores. This model, visualized
as a straight line, allows you to predict the anticipated exam score for
a student who dedicates a specific number of hours to studying. This
predictive power is undeniably valuable.

However, linear regression goes beyond mere prediction. It unveils the
\textbf{underlying nature} of the relationship between variables. The
slope of the line you establish serves as a vital clue. A steeper slope
suggests that additional study hours translate into a more significant
increase in exam scores. Conversely, a gentler slope indicates a less
pronounced impact of study hours on exam performance.

In essence, linear regression equips us with a two-pronged approach:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Prediction:} We can leverage the model to forecast outcomes
  based on new data points.
\item
  \textbf{Understanding Relationships:} By analyzing the slope and other
  properties of the line, we gain insights into how changes in one
  variable (study hours) influence the other (exam scores).
\end{enumerate}

It's important to remember that the world isn't always perfectly linear.
However, linear regression serves as a robust foundation for data
analysis, providing a framework to explore connections and make informed
decisions based on the information gleaned from our data.

Let's understand what it means for us in terms of our workflow. The
workflow for the linear regression problem would be:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  We would be given some observations of both - independent variable(s)
  and dependent variable.
\item
  we graph these data points, using a coordinate system (like Cartesian
  system). Each value is represented by a dot. Such a diagram is called
  a scatter-plot diagram.
\item
  After graphing the points onto a scatter plot diagram, linear
  regression analysis seeks to find the best-fit line to fit the points
  as closely as possible.
\item
  This best-fit line is a line, which minimizes the distance between the
  points falling above or below the lines.
\end{enumerate}

\href{https://www.fiverr.com/resources/guides/data/linear-regression-101}{Linear
Regression 101: What Is It And How Is It Done? \textbar{} Fiverr}

\section{Unveiling the Assumptions Behind Linear
Regression}\label{unveiling-the-assumptions-behind-linear-regression}

While linear regression offers a powerful lens for analyzing
relationships, its effectiveness hinges on certain underlying
assumptions. These assumptions, akin to the ground rules of the game,
ensure the validity of the results we obtain. Let's delve into these key
assumptions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Linearity:} The core principle of linear regression lies in
  its name - \textbf{linearity}. This assumption dictates that the
  relationship between the two variables we're investigating is
  \textbf{straight-line} in nature. In simpler terms, when one variable
  increases or decreases, the other variable changes in a consistent,
  proportional manner, much like points scattered along a straight line.
\item
  \textbf{Independence of Errors:} This assumption emphasizes that the
  \textbf{errors} (the difference between the actual data point and the
  value predicted by the model) are \textbf{independent} of each other.
  Imagine each error term as a random fluctuation; these fluctuations
  shouldn't be influenced by the errors associated with other data
  points.
\item
  \textbf{Homoscedasticity:} This tongue-twister of a term refers to the
  notion of \textbf{constant variance} of the errors. In simpler terms,
  the spread of the errors (how far they deviate from the predicted
  value) should be \textbf{consistent} across all levels of the
  independent variable (the variable we believe causes the change in the
  other variable).
\item
  \textbf{Normality of Errors:} This assumption posits that the errors
  associated with our data follow a \textbf{normal distribution}, often
  referred to as a bell curve. This characteristic distribution helps
  ensure the reliability of the statistical tests we perform to assess
  the model's validity.
\end{enumerate}

By adhering to these assumptions, we create a solid foundation for
interpreting the results of our linear regression analysis. However,
it's crucial to remember that real-world data may not always perfectly
satisfy these assumptions. Fortunately, there are techniques to address
potential violations and ensure the robustness of our analysis. We'll
explore these strategies in the upcoming chapters!

\section{Example in R}\label{example-in-r}

For understanding regression, we can generate a dummy dataset, and
create a regression model on the basis of the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dummy }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{y =} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{),}\AttributeTok{x =} \FunctionTok{rpois}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

In the code above, we have created a dummy data. The \texttt{rnorm(n)}
function generates n number of data points based on normal distribution.
The default mean and standard deviation are 0 and 1 respectively.
Similarly, the \texttt{rpois(n,l)} function generates n number of data
points based on poisson distribution, with \lambda = l. We can plot the
data to explore it visually. We will use \texttt{ggplot2} package to
create this scatterplot diagram.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(dummy)}\SpecialCharTok{+}\FunctionTok{aes}\NormalTok{(x,y)}\SpecialCharTok{+}\FunctionTok{geom\_point}\NormalTok{()}\SpecialCharTok{+}\FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Scatterplot Diagram of X and Y"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}[h]

\centering{

\includegraphics{lm_files/figure-pdf/fig-scatterplot-1.pdf}

}

\caption{\label{fig-scatterplot}Scatterplot of X and Y}

\end{figure}%

Now we can create a regression model from this dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y}\SpecialCharTok{\textasciitilde{}}\NormalTok{x, }\AttributeTok{data =}\NormalTok{ dummy)}
\end{Highlighting}
\end{Shaded}

This model stores a lot of information, but it is difficult to
understand and get the meaning out of it. So, one way is to use the
\texttt{summary} function on this \texttt{model1} object.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = y ~ x, data = dummy)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.6342 -0.4445  0.0324  0.6090  2.7336 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  0.24693    0.20632   1.197    0.234
x           -0.05627    0.05672  -0.992    0.324

Residual standard error: 1.051 on 98 degrees of freedom
Multiple R-squared:  0.009944,  Adjusted R-squared:  -0.0001589 
F-statistic: 0.9843 on 1 and 98 DF,  p-value: 0.3236
\end{verbatim}

The problem with this summary object is that it is not a data.frame. It
is difficult to put this object in a research paper or any other
academic submisison. So, we can use the \texttt{easystats} packages for
this. The \texttt{model\_parameters} function would show us the
parameters (aka coefficients) of the model, and the
\texttt{model\_performance} function will show us the effectiveness of
the regression model. We can also use the \texttt{display} function to
beautify the table in the output.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model1 }\SpecialCharTok{|\textgreater{}} \FunctionTok{model\_parameters}\NormalTok{() }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{display}\NormalTok{(}\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{, }\AttributeTok{caption =} \StringTok{"Regression Parameters"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lccccc@{}}

\caption{\label{tbl-regression-params}Regression Parameters}

\tabularnewline

\toprule\noalign{}
Parameter & Coefficient & SE & 95\% CI & t(98) & p \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
(Intercept) & 0.25 & 0.21 & (-0.16, 0.66) & 1.20 & 0.234 \\
x & -0.06 & 0.06 & (-0.17, 0.06) & -0.99 & 0.324 \\

\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model1 }\SpecialCharTok{|\textgreater{}} \FunctionTok{model\_performance}\NormalTok{() }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{display}\NormalTok{(}\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{, }\AttributeTok{caption =} \StringTok{"Regression Effectiveness"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lcccccc@{}}

\caption{\label{tbl-regression-effectiveness}Regression Effectiveness}

\tabularnewline

\caption{Regression Effectiveness}\tabularnewline
\toprule\noalign{}
AIC & AICc & BIC & R2 & R2 (adj.) & RMSE & Sigma \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
AIC & AICc & BIC & R2 & R2 (adj.) & RMSE & Sigma \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
297.71 & 297.96 & 305.53 & 9.94e-03 & -1.59e-04 & 1.04 & 1.05 \\

\end{longtable}

\subsection{Interpretation of Regression
Model}\label{interpretation-of-regression-model}

- The intercept is statistically non-significant and negative (beta =
-0.16, 95\% CI {[}-0.59, 0.27{]}, t(98) = -0.74, p = 0.461; Std. beta =
-5.50e-18, 95\% CI {[}-0.20, 0.20{]}).

\begin{itemize}
\tightlist
\item
  The effect of x is statistically non-significant and positive (beta =
  0.07, 95\% CI {[}-0.04, 0.17{]}, t(98) = 1.24, p = 0.219; Std. beta =
  0.12, 95\% CI {[}-0.07, 0.32{]}).
\end{itemize}

The model explains a statistically not significant and very

weak proportion of variance (R\^{}2 = 0.02, F(1, 98) = 1.53, p =

0.219, adj. R\^{}2 = 5.32e-03).

\subsection{Non-Linear Relationship in
Regression}\label{non-linear-relationship-in-regression}

Sometimes, the relationship between the dependent and independent
variable is not linear, but quadratic. This can be understood either
from the scatter plot diagram or from theoretical considerations. In
mathematical terms, the relationship is

\begin{equation}\phantomsection\label{eq-quadratic}{
Y = \beta_0 + \beta_1*X^2 + \gamma
}\end{equation}

where X and Y are independent and dependent variables, respectively.
This is still considered ``Linear Regression'', because we are
interested in the the linearity of the coefficient term (i.e., \beta),
not the linearity of the variables. In the equation above, both the
coefficients (\(\beta_0\) and \(\beta_1\)) are linear, and so is the
error term, \(\gamma\) in this equation.

\section{Interval Estimation and Hypothesis
Testing}\label{interval-estimation-and-hypothesis-testing}

Linear regression empowers us to understand relationships and make
predictions. But remember, the world of data isn't perfect, and our
models are based on samples, not the entire population. This inherent
uncertainty is where \textbf{interval estimation} steps in.

Imagine you estimated a straight line to represent the connection
between house size (square footage) and selling price. This line
predicts the average selling price for a given house size. But what if a
single house is much larger or smaller than those in your sample? The
predicted price from the model might not be the exact selling price.

Interval estimation tackles this by providing a \textbf{range of
plausible values} for the outcome variable (selling price) at a specific
level of the independent variable (house size). This range, called a
\textbf{confidence interval}, gives us a sense of the \textbf{precision}
of our prediction.

Here's how it works:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  We choose a \textbf{confidence level}, typically 90\% or 95\%. This
  indicates the probability that the true value falls within the
  constructed interval.
\item
  We leverage the concept of the \textbf{standard error of the
  estimate}. This statistical measure reflects the average amount our
  predictions might deviate from the actual values.
\item
  By incorporating the chosen confidence level and the standard error,
  we calculate the \textbf{upper and lower bounds} of the confidence
  interval. This range represents the values within which we are
  confident (based on the chosen level) the true outcome variable will
  lie for a given independent variable value.
\end{enumerate}

\textbf{What does this tell us?}

A narrower confidence interval indicates a more precise prediction. The
model is more certain about the range of potential selling prices for a
specific house size. Conversely, a wider interval reflects greater
uncertainty. The model can't pinpoint the exact selling price as
confidently.

\textbf{Interval estimation is crucial because:}

\begin{itemize}
\item
  It acknowledges the inherent uncertainty in our predictions.
\item
  It allows us to communicate the \textbf{precision} of our findings.
\item
  It helps us assess the \textbf{reliability} of the model for
  predictions.
\end{itemize}

By incorporating interval estimation, we paint a more nuanced picture
when interpreting the results of linear regression analysis. We not only
provide a predicted value but also quantify the associated uncertainty,
making our analysis more informative and reliable.

Let us understand interval estimation with an example of a real dataset.
We will use the \texttt{mtcars} dataset, which comes bundled with R.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(mpg}\SpecialCharTok{\textasciitilde{}}\NormalTok{disp, }\AttributeTok{data =}\NormalTok{ mtcars)}
\end{Highlighting}
\end{Shaded}

In the code above, we fitted a model on the \texttt{mtcars} dataset,
where Miles Per Gallon, or \texttt{mpg} is explained by Displacement
(cubic inches), or \texttt{disp} variable. The \beta coefficient for
\texttt{disp} is -0.0412151. The 95\% confidence interval of the
coefficients can be found using the \texttt{confint} function in R.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{confint}\NormalTok{(mod1) }\SpecialCharTok{|\textgreater{}} \FunctionTok{kbl}\NormalTok{(}\AttributeTok{digits =} \DecValTok{4}\NormalTok{,}\AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{align =} \StringTok{"c"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tbl-confint}Confidence Interval of Model Coefficients}

\centering{

\begin{tabular}[t]{lcc}
\toprule
  & 2.5 \% & 97.5 \%\\
\midrule
(Intercept) & 27.0884 & 32.1113\\
disp & -0.0508 & -0.0316\\
\bottomrule
\end{tabular}

}

\end{table}%

In the code above, the \texttt{confint} function is used to find out the
confidence interval, while the other functions are used to format the
resulting table. The last row of the table suggests that the 95\%
confidence interval for the \texttt{disp} variable is between (-0.0508)
and (-0.0316).

\section{Hypothesis Testing}\label{hypothesis-testing}

Linear regression equips us to explore relationships and make
predictions, but are these connections merely due to chance, or do they
hold true significance? This is where \textbf{hypothesis testing} enters
the scene. Imagine you suspect a link between coffee consumption and
alertness levels. Regression analysis can tell you if there's a
relationship, but hypothesis testing helps determine if this connection
is statistically \textbf{meaningful}.

Here's the framework:

\textbf{Formulating Hypotheses:}

\textbf{Null Hypothesis (H₀):} This hypothesis proposes that there's
\textbf{no significant relationship} between the independent and
dependent variables (e.g., coffee consumption has no impact on alertness
levels).

\textbf{Alternative Hypothesis (H₁):} This hypothesis stands in
opposition to the null hypothesis, suggesting that a \textbf{significant
relationship} exists (e.g., coffee consumption does influence alertness
levels).

\textbf{Choosing a Significance Level:} This threshold, typically set at
5\%, determines how likely we are to reject the null hypothesis even
when it's actually true (a false positive). A lower significance level
indicates a stricter test, requiring stronger evidence to reject the
null hypothesis.

\textbf{Test Statistic and p-value:} We employ statistical tests like
the t-test or F-test to calculate a \textbf{test statistic}. This value
reflects the strength of the evidence against the null hypothesis. A
higher (absolute) value suggests a stronger case for rejecting the null
hypothesis.

We then calculate the \textbf{p-value}, which represents the probability
of observing a test statistic as extreme or more extreme than the one we
calculated, assuming the null hypothesis is true. A lower p-value
indicates less likelihood of observing such an extreme result by chance
alone.

\textbf{Decision Making:} Based on the chosen significance level and the
p-value, we make a decision:

\textbf{Reject H₀:} If the p-value is lower than the significance level,
we reject the null hypothesis. There's sufficient evidence to suggest a
significant relationship between the variables.

\textbf{Fail to Reject H₀:} If the p-value is greater than the
significance level, we fail to reject the null hypothesis. We cannot
conclude a statistically significant relationship at this level of
significance. However, this doesn't necessarily imply there's no
connection; it just means we don't have enough evidence to disprove the
null hypothesis.

R automatically performs a hypothesis testing, along with presenting
regression summary. For example, in the
Table~\ref{tbl-regression-params}, the last column titled ``p'' conducts
a two-way hypothesis testing for the t-value shown in the previous
column, titled ``t(98)'', (where 98 number shows the degrees of freedom)
whether the t-value is significantly different from zero. In this case,
the null and the alternative hypothesis are as follows:

\[
H_0: t = 0
\] \[
H_1: t \neq 0
\]

Given that both the p-values (0.234 and 0.324) are greater than the
significance level (0.05), we fail to reject the null hypothesis. In
other words, we believe that both, the intercept and x, are
statistically significant in order to explain the variation in the
dependent variable, y.

\section{Prediction}\label{prediction}

Linear regression not only unveils relationships between variables but
also empowers us to \textbf{predict} future outcomes. Imagine you're a
business analyst trying to forecast sales based on advertising spending.
R, a powerful statistical programming language, provides tools to
leverage your regression model for predictions.

Here's a breakdown of the prediction process with an example using R
code:

\textbf{1. Sample Data and Model Fitting:}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Simulate some data for advertising spend (ad\_spend) and sales (sales) }
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{) }
\NormalTok{ad\_spend }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\AttributeTok{mean =} \DecValTok{100}\NormalTok{, }\AttributeTok{sd =} \DecValTok{15}\NormalTok{) }
\NormalTok{sales }\OtherTok{\textless{}{-}} \DecValTok{50} \SpecialCharTok{+} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ ad\_spend }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \DecValTok{10}\NormalTok{)  }
\CommentTok{\# Fit the linear regression model}
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(sales }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ad\_spend)}
\end{Highlighting}
\end{Shaded}

In this code:

\begin{itemize}
\item
  We simulate data for advertising spend and sales.
\item
  The \texttt{lm} function fits a linear regression model where
  \texttt{sales} is the dependent variable and \texttt{ad\_spend} is the
  independent variable.
\end{itemize}

\textbf{2. Predicting Sales for a New Advertising Spend Value:}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Predict sales for an ad spend of $120 }
\NormalTok{new\_spend }\OtherTok{\textless{}{-}} \DecValTok{120} 
\NormalTok{predicted\_sales }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model, }\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{ad\_spend =}\NormalTok{ new\_spend))  }
\FunctionTok{cat}\NormalTok{(}\StringTok{"Predicted sales for an ad spend of $"}\NormalTok{, new\_spend, }\StringTok{":"}\NormalTok{, predicted\_sales, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Predicted sales for an ad spend of $120:288.2723
\end{verbatim}

This code:

\begin{itemize}
\item
  Defines a new advertising spend value of \$120.
\item
  The \texttt{predict} function leverages the fitted model
  (\texttt{model}) to predict sales for this new data point (represented
  as a data frame with the new \texttt{ad\_spend} value).
\item
  The \texttt{cat} function displays the predicted sales value.
\end{itemize}

This indicates that based on the model, sales are predicted to be around
\$290 for an advertising spend of \$120.

The key difference between prediction intervals and confidence intervals
in the \texttt{predict} function of R lies in what they are trying to
estimate:

\begin{itemize}
\item
  \textbf{Prediction Interval:} Focuses on a \textbf{single future
  observation}. It estimates the range within which a \textbf{new
  individual value} of the dependent variable is likely to fall, given a
  specific value of the independent variable.
\item
  \textbf{Confidence Interval:} Focuses on the \textbf{mean prediction}.
  It estimates the range that's likely to contain the \textbf{average
  value} of the dependent variable for a specific value of the
  independent variable.
\end{itemize}

Here's a breakdown to illustrate the concept:

\textbf{Scenario:} Predicting sales based on advertising spend.

\begin{itemize}
\item
  \textbf{Confidence Interval:} If you set a 95\% confidence interval
  for predicted sales at an ad spend of \$120, it indicates that you're
  95\% confident the \textbf{average sales} for that advertising spend
  will fall within that interval.
\item
  \textbf{Prediction Interval:} A 95\% prediction interval for the same
  scenario estimates the range that's likely to encompass a
  \textbf{single new sales value} at an ad spend of \$120.
\end{itemize}

\textbf{R Code Demonstration:}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Simulate data for advertising spend (ad\_spend) and sales (sales)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{) }
\NormalTok{ad\_spend }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\AttributeTok{mean =} \DecValTok{100}\NormalTok{, }\AttributeTok{sd =} \DecValTok{15}\NormalTok{) }
\NormalTok{sales }\OtherTok{\textless{}{-}} \DecValTok{50} \SpecialCharTok{+} \DecValTok{2} \SpecialCharTok{*}\NormalTok{ ad\_spend }\SpecialCharTok{+} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \DecValTok{10}\NormalTok{)  }
\CommentTok{\# Fit the linear regression model}
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(sales }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ad\_spend)  }
\CommentTok{\# New advertising spend value}
\NormalTok{new\_spend }\OtherTok{\textless{}{-}} \DecValTok{120}  
\CommentTok{\# Confidence Interval for Mean Prediction }
\NormalTok{conf\_interval }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model, }\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{ad\_spend =}\NormalTok{ new\_spend), }\AttributeTok{interval =} \StringTok{"confidence"}\NormalTok{)  }
\CommentTok{\# Prediction Interval for a New Observation }
\NormalTok{prediction\_interval }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model, }\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{ad\_spend =}\NormalTok{ new\_spend), }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{)  }
\FunctionTok{cat}\NormalTok{(}\StringTok{"Predicted sales for an ad spend of $"}\NormalTok{, new\_spend, }\StringTok{":"}\NormalTok{, }\FunctionTok{summary}\NormalTok{(predicted\_sales), }\AttributeTok{sep =} \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Predicted sales for an ad spend of $
120
:
288.2723
288.2723
288.2723
288.2723
288.2723
288.2723
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"95\% Confidence Interval for Mean Prediction:"}\NormalTok{, conf\_interval[,}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{)], }\AttributeTok{sep =} \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
95% Confidence Interval for Mean Prediction:
288.2723
291.5374
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"95\% Prediction Interval for a New Observation:"}\NormalTok{, prediction\_interval[,}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{)], }\AttributeTok{sep =} \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
95% Prediction Interval for a New Observation:
288.2723
307.8106
\end{verbatim}

\textbf{Key Points:}

\begin{itemize}
\item
  The confidence interval for the mean prediction is much narrower than
  the prediction interval for a new observation. This reflects the
  inherent uncertainty in predicting a single future value compared to
  the average sales across multiple observations.
\item
  Prediction intervals are generally wider because they account for the
  variability around the average sales figure, along with the
  uncertainty in the model itself.
\end{itemize}

In conclusion, choosing between a confidence interval and a prediction
interval depends on your goal:

\begin{itemize}
\item
  If you're interested in the \textbf{average sales} for a specific
  advertising spend, use the confidence interval.
\item
  If you want to estimate the range for a \textbf{single new sales
  value}, then the prediction interval is more appropriate.
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Multiple Linear Regression}\label{multiple-linear-regression}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Extending regression analysis to multiple independent variables}

\item{Building and interpreting multiple linear regression models in R}

\item{Handling multicollinearity and selecting significant predictors in an economic context}

\item{Model evaluation and diagnostics in econometric regression}

\item{Application of multiple linear regression in economic analysis using R}

\end{itemize}

\end{objectives}

\subsection{Introduction}\label{introduction-2}

In the previous chapter, we saw simple linear regression, in which we
attempted to understand the relationship between two variables - one
called independent variable and the other called the dependent variable.
Multiple linear regression is a statistical technique that allows us to
analyze the relationship between two or more independent variables and a
dependent variable. It is an extension of simple linear regression,
which only involves one independent variable. Multiple linear regression
is used to predict the value of a dependent variable based on the values
of two or more independent variables. It is commonly used in fields such
as economics, finance, and social sciences.

\section{Assumptions of Multiple Linear
Regression}\label{assumptions-of-multiple-linear-regression}

There are a few assumptions of multiple linear regression. They are as
follows:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Linearity of coefficients and error terms

  The coefficients (\(\beta\)) and the error terms (\(\epsilon\)) are
  linear. The variables themselves might be linear or polynomials. But
  the coefficients and error terms must be linear.
\item
  The error term (\(\epsilon\)) has population mean zero.

  In particular, the error term is normally distributed with the
  population mean of zero. If the population mean of the error term is
  other than zero, it means at least some part of the error term is
  predictable. Such a predictable part should be kept in the regression
  equation itself, not in error term. The error term should contain only
  random error, which can be attributed to chance. When the population
  mean is not equal to zero, statisticians call it ``bias''.
\item
  None of the independent variables is correlated with the error term.

  If any of the independent variable is correlated with the error term,
  it means it is possible to predict the error term. So, in such case,
  it is better to put this information in the regression equation
  itself. As we said in the previous point, the error term should
  contain only the random error, which explains the variability of the
  dependent variable. If the error term also explains the variability of
  any of the independent variable, it is not an error per se.
\item
  Observations in the error term are independent of one another (i.e.,
  not correlated with one another). If error terms are correlated, it
  means it is possible to predict the error term of the next
  observation, using the information of the error term in the first
  observation. And any information, which can be used to predict the
  error term, should be put in the regression equation itself. The error
  terms should contain only the random component.
\item
  The variance in the error terms remain constant for all the
  observations. This assumption is also called homoskedasticity. PENDING
\item
  There is no perfect correlation between any of the independent
  variable with the dependent variable. If there is a perfect
  correlation between any two variables, then one of the two variables
  is unnecessary.
\end{enumerate}

\section{Multiple Linear Regression: A Practical
Example}\label{multiple-linear-regression-a-practical-example}

Let's look at the dataset from the book ``Basic Econometrics'' by
Damodar Gujarati, et al (The Special Indian Economy Edition). The Table
7.6 shows consumption of Chicken in 22 states and union territories in
India. The variables are as follows:

\begin{itemize}
\item
  Y: Consumption of chicken (in kg)
\item
  X2: Price of chicken (Rs. Per kg)
\item
  X3: Price of fish (Rs. Per kg)
\item
  X4: Per capita income (Rs. Thousands at 1993-94 prices)
\end{itemize}

(Note: You need to download the \texttt{Gujarati5sie} package from
github using the command
\texttt{devtools::install\_github("bhattmaulik/Gujarati5sie")}. Once you
have installed this package, you can check the documentation of any of
the table contained in the package using the \texttt{?table} syntex. For
example, \texttt{?Table7.6} will show you the documentation for the
Table 7.6 in the package.)

We can load the dataset, and inspect the variables in the dataset.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#devtools::install\_github("bhattmaulik/Gujarati5sie) }
\CommentTok{\#to download the "Gujarati5sie" package}
\CommentTok{\#which contains the dataset}
\CommentTok{\#install.packages("GGally)}
\CommentTok{\#to install the GGally package}
\CommentTok{\# library(easystats)}
\CommentTok{\# library(Gujarati5sie)}
\CommentTok{\# library(GGally)}
\FunctionTok{data}\NormalTok{(}\StringTok{"Table7.6"}\NormalTok{)}
\CommentTok{\#to load the dataset from Table 7.6}
\FunctionTok{ggpairs}\NormalTok{(Table7}\FloatTok{.6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Multiple_Regression_files/figure-pdf/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#to check correlation among variables in the dataset}
\end{Highlighting}
\end{Shaded}

We can see that Y has negative correlation with X2 and X3, and slightly
negative correlation with X4 also. This looks \textbf{usual more or
less,} because according to theory, the consumption of a commodity would
have negative relationship with its price. Fish is a competitor for
chicken, so consumption of chicken should have positive correlation with
the price of fish, which is not the case in this dataset.

Let's fit a linear regression model on the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Y}\SpecialCharTok{\textasciitilde{}}\NormalTok{X2}\SpecialCharTok{+}\NormalTok{X3}\SpecialCharTok{+}\NormalTok{X4, }\AttributeTok{data =}\NormalTok{ Table7}\FloatTok{.6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We can see that multiple regression also requires the \texttt{lm}
function, just like classical linear regression model. To add more
variables in the regression model, we have to use the \texttt{+} sign on
the right hand side of the \texttt{\textasciitilde{}} sign.

PENDING

Model Building Strategies

Often, regression model building needs multiple models. In the first
step, the analyst needs to know the possibly relevant independent
variables, which might affect the dependent variable. Then the data is
collected for these variables. After data collection, the analyst would
fit a regression model, and find coefficients for the model. But that's
not the end of the regression. The analyst would need to check whether
the model fulfills the assumptions of the regression model. If there are
violations, the analyst would need to create another model. Often, a
step-wise regression process is adopted.

In a step-wise regression model, independent variables would be added or
removed one-by-one and the analyst would monitor its impact on the
decision criteria (often, \(R^2\) or adjusted R\textsuperscript{2}, but
it could be AIC or BIC also). The analyst would choose the model, which
optimizes the decision criteria: for R\textsuperscript{2} and adjusted
R\textsuperscript{2}, the more the better, while for AIC and BIC, the
less is the better.

also see pdf on steps to follow in multiple regression model building

\href{https://bookdown.org/ripberjt/qrmbook/multiple-regression-and-model-building.html}{13
Multiple Regression and Model Building \textbar{} Quantitative Research
Methods for Political Science, Public Policy and Public Administration:
4th Edition With Applications in R (bookdown.org)}

Model Diagnostics

\href{https://faculty.nps.edu/rbassett/_book/multiple-regression-models.html}{Chapter
13 Multiple Regression Models \textbar{} Introduction to Statistics and
Data Science (nps.edu)}

\href{https://web.stanford.edu/class/stats191/notebooks/Diagnostics_for_multiple_regression.html}{Diagnostics\_for\_multiple\_regression
(stanford.edu)}

Interpretation of Results of Multiple Linear Regression

\href{https://www.scribbr.com/statistics/linear-regression-in-r/}{Linear
Regression in R \textbar{} A Step-by-Step Guide \& Examples
(scribbr.com)}

\href{http://svmiller.com/blog/2014/08/reading-a-regression-table-a-guide-for-students/}{Reading
a Regression Table: A Guide for Students \textbar{} Steven V. Miller
(svmiller.com)}

Multicollinearity and Variable Selection

\href{https://statisticsbyjim.com/regression/multicollinearity-in-regression-analysis/}{Multicollinearity
in Regression Analysis: Problems, Detection, and Solutions - Statistics
By Jim}

\href{https://www.upgrad.com/blog/multicollinearity-in-regression-analysis/}{Multicollinearity
in Regression Analysis: Everything You Need to Know \textbar{} upGrad
blog}

Model Selection Strategies

\href{https://testscience.org/analyze-test-data/inferential/benefits-of-statistical-modeling/model-selection/\#:~:text=There\%20are\%20several\%20model\%20building\%20strategies\%20available\%20using,to\%20regularization\%20approaches\%20\%28ridge\%20regression\%2C\%20LASSO\%2C\%20elastic\%20net\%29.}{Model
Selection -- Test Science 3.0}

\href{https://towardsdatascience.com/evaluation-metrics-model-selection-in-linear-regression-73c7573208be}{Evaluation
metrics \& Model Selection in Linear Regression \textbar{} by NVS
Yashwanth \textbar{} Towards Data Science}

\bookmarksetup{startatroot}

\chapter{Regression Analysis with Dummy
Variables}\label{regression-analysis-with-dummy-variables}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Incorporating categorical variables in regression analysis}

\item{Creating and interpreting dummy variables in R}

\item{Dummy variable pitfalls and remedies in econometric modeling}

\item{Examples and case studies of dummy variable regression in economics using R}

\end{itemize}

\end{objectives}

\begin{itemize}
\item
  Incorporating categorical variables in regression analysis
\item
  Creating and interpreting dummy variables in R
\item
  Dummy variable pitfalls and remedies in econometric modeling
\item
  Examples and case studies of dummy variable regression in economics
  using R
\end{itemize}

\href{http://sthda.com/english/articles/40-regression-analysis/163-regression-with-categorical-variables-dummy-coding-essentials-in-r/}{Regression
with Categorical Variables: Dummy Coding Essentials in R - Articles -
STHDA}

\href{http://www.personal.rhul.ac.uk/uhte/006/ec2203/Use\%20and\%20Interpretation\%20of\%20Dummy\%20Variables.pdf}{Microsoft
Word - Use and Interpretation of Dummy Variables.doc (rhul.ac.uk)}

Categorical variables are the variables, which divide the observations
in different groups. These categorical variables are also called
factors, dummy variables, or qualitative variables. For example, gender
of respondent (Male v/s Female) is a factor or dummy variable. The two
values ``Male'' and ``Female'' are the levels of the factor. There are
packages in R, e.g., \texttt{forcats}, which deal with factor variables.

In a linear regression model, the dependent variable would be a numeric
(or continuous) variable. But on the independent variable side, one or
more variable(s) can be factors. In such cases, we need to take some
extra steps. These steps typically involve ``coding'' dummy variables.
We can understand this by a practical example in R.

The \texttt{penguins} dataset from the \texttt{palmerpenguins} package
contains several factor variables, like \texttt{species},
\texttt{island} and \texttt{sex}. We will use \texttt{species} as the
independent variable, and the \texttt{body\_mass\_g} (which captures the
body mass in grams) as the dependent variables. By using the
\texttt{levels} function, we can see that there are three levels of the
\texttt{species} variable: Adelie, Chinstrap, and Gentoo.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(palmerpenguins)}
\NormalTok{penguins }\OtherTok{\textless{}{-}}\NormalTok{ palmerpenguins}\SpecialCharTok{::}\NormalTok{penguins}
\FunctionTok{levels}\NormalTok{(penguins}\SpecialCharTok{$}\NormalTok{species)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Adelie"    "Chinstrap" "Gentoo"   
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(body\_mass\_g}\SpecialCharTok{\textasciitilde{}}\NormalTok{species, }\AttributeTok{data =}\NormalTok{ penguins)}
\FunctionTok{summary}\NormalTok{(mod1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Call:
lm(formula = body_mass_g ~ species, data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-1126.02  -333.09   -33.09   316.91  1223.98 

Coefficients:
                 Estimate Std. Error t value Pr(>|t|)    
(Intercept)       3700.66      37.62   98.37   <2e-16 ***
speciesChinstrap    32.43      67.51    0.48    0.631    
speciesGentoo     1375.35      56.15   24.50   <2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 462.3 on 339 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.6697,    Adjusted R-squared:  0.6677 
F-statistic: 343.6 on 2 and 339 DF,  p-value: < 2.2e-16
\end{verbatim}

In the code above, we created a linear regression model, where
\texttt{body\_mass\_g} is the dependent variable, and the
\texttt{species} is the independent variable. When we take
\texttt{summary} of this regression model, we can see that there are
three coefficients: Intercept, and the two levels of \texttt{species}
variable, Chinstrap and Gentoo. The third level of the \texttt{species}
variable (i.e., Adelie) is missing in this equation.

This is because Adelie is the base level in the equation. You can
understand this from the \texttt{contrasts} function in the code given
below:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{contrasts}\NormalTok{(penguins}\SpecialCharTok{$}\NormalTok{species)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
          Chinstrap Gentoo
Adelie            0      0
Chinstrap         1      0
Gentoo            0      1
\end{verbatim}

You can see that Adelie is coded as 0 (zero) in this table. Therefore,
the interpretation of the coefficients would also change accordingly.
The coefficient of 32.43 for \texttt{speciesChinstrap} means that on
average, the body mass of penguins belonging to Chinstrap species would
be 32.43 grams more than a penguin belonging to the Adelie species
(assuming all other factors equal). Similarly, the body mass of a
penguin belonging to Gentoo category would be more than the Adelie
category of penguin by 1,375.35 grams on average, assuming other factors
equal.

\bookmarksetup{startatroot}

\chapter{Heteroscedasticity and Robust
Regression}\label{heteroscedasticity-and-robust-regression}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Understanding heteroscedasticity and its implications}

\item{Addressing heteroscedasticity using robust regression techniques in R}

\item{Interpreting robust regression results in an economic context}

\item{Practical examples and exercises showcasing robust regression in econometrics}

\end{itemize}

\end{objectives}

\begin{itemize}
\item
  Understanding heteroscedasticity and its implications
\item
  Addressing heteroscedasticity using robust regression techniques in R
\item
  Interpreting robust regression results in an economic context
\item
  Practical examples and exercises showcasing robust regression in
  econometrics
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Time Series Regression}\label{time-series-regression}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Introduction to time series data in econometrics}

\item{Time series regression models in R for economic analysis}

\item{Dealing with autocorrelation and lagged variables}

\item{Forecasting with time series regression models in R}

\item{Applications of time series regression in economic forecasting}

\end{itemize}

\end{objectives}

\begin{itemize}
\item
  Introduction to time series data in econometrics
\item
  Time series regression models in R for economic analysis
\item
  Dealing with autocorrelation and lagged variables
\item
  Forecasting with time series regression models in R
\item
  Applications of time series regression in economic forecasting
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Introduction to Logistic
Regression}\label{introduction-to-logistic-regression}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Basics of logistic regression in econometrics}

\item{Estimating logistic regression models in R}

\item{Interpreting logistic regression coefficients and odds ratios}

\item{Applications of logistic regression in economic research using R}

\end{itemize}

\end{objectives}

\begin{itemize}
\item
  Basics of logistic regression in econometrics
\item
  Estimating logistic regression models in R
\item
  Interpreting logistic regression coefficients and odds ratios
\item
  Applications of logistic regression in economic research using R
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Model Evaluation and
Selection}\label{model-evaluation-and-selection}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Evaluating model performance and goodness-of-fit measures in econometrics}

\item{Validation techniques for econometric regression models}

\item{Comparing and selecting models using information criteria}

\item{Cross-validation and bootstrapping for robust model assessment in econometrics}

\end{itemize}

\end{objectives}

\begin{itemize}
\item
  Evaluating model performance and goodness-of-fit measures in
  econometrics
\item
  Validation techniques for econometric regression models
\item
  Comparing and selecting models using information criteria
\item
  Cross-validation and bootstrapping for robust model assessment in
  econometrics
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Practical Tips and Resources for Econometric
Regression}\label{practical-tips-and-resources-for-econometric-regression}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Data preparation and preprocessing tips for econometric analysis}

\item{Handling missing data and outliers in regression analysis}

\item{Dealing with endogeneity and instrumental variables}

\item{Additional resources for further learning and practice in econometrics with R}

\end{itemize}

\end{objectives}

\begin{itemize}
\item
  Data preparation and preprocessing tips for econometric analysis
\item
  Handling missing data and outliers in regression analysis
\item
  Dealing with endogeneity and instrumental variables
\item
  Additional resources for further learning and practice in econometrics
  with R
\end{itemize}

It is said that a data scientist spends 70\% of his/her time in data
cleaning rather than data analysis. Therefore, in this chapter, we will
discuss various techniques to prepare and preprocess the data for
econometric analysis. In the chapter Chapter~\ref{sec-getting-started},
we introduced some methods of data pre-processing, which were
essentially sub-setting the data from a larger set and creating new
variables from the existing ones. In this chapter, we will deal with
data cleaning, finding missing values, finding columns where a date is
stored as a number (for example, importing data from Microsoft Excel),
etc.

\section{Data Cleaning}\label{data-cleaning}

The very first step of data cleaning starts with the data import itself.
When you import data from \texttt{csv} file (using
\texttt{readr::read\_csv} function) or \texttt{Microsoft\ Excel} file
(using the \texttt{readxl::read\_excel} function), you have the option
of cleaning the names directly while importing the data. Both of these
functions have an argument called \texttt{.name\_repair}, which
determines how the column names would be changed after importing the
data. The default method is the keep the names \texttt{unique}, which
means, if the dataset contains multiple columns having the same name, it
would change the name to \texttt{name1}, \texttt{name2}, etc. It is also
possible to provide a function to this argument. We can see an example
in the code below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}\CommentTok{\#load the package}
\FunctionTok{read\_excel}\NormalTok{(}\FunctionTok{readxl\_example}\NormalTok{(}\StringTok{"datasets.xlsx"}\NormalTok{), }\AttributeTok{.name\_repair =} \StringTok{"unique"}\NormalTok{) }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{() }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{kbl}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tbl-name-repair}Making Unique Names in a Dataset}

\centering{

\begin{tabular}[t]{r|r|r|r|l}
\hline
Sepal.Length & Sepal.Width & Petal.Length & Petal.Width & Species\\
\hline
5.1 & 3.5 & 1.4 & 0.2 & setosa\\
\hline
4.9 & 3.0 & 1.4 & 0.2 & setosa\\
\hline
4.7 & 3.2 & 1.3 & 0.2 & setosa\\
\hline
4.6 & 3.1 & 1.5 & 0.2 & setosa\\
\hline
5.0 & 3.6 & 1.4 & 0.2 & setosa\\
\hline
5.4 & 3.9 & 1.7 & 0.4 & setosa\\
\hline
\end{tabular}

}

\end{table}%

Now, instead of keeping the default \texttt{unique} names, we can change
it using \texttt{make\_clean\_names} function from the \texttt{janitor}
package. For this to work, you must have installed the \texttt{janitor}
package in your system.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{read\_excel}\NormalTok{(}\FunctionTok{readxl\_example}\NormalTok{(}\StringTok{"datasets.xlsx"}\NormalTok{),}
           \AttributeTok{.name\_repair =}\NormalTok{ janitor}\SpecialCharTok{::}\NormalTok{make\_clean\_names) }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{() }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{kbl}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tbl-name-repair-janitor}Making Clean Names in a Dataset
using janitor package}

\centering{

\begin{tabular}[t]{r|r|r|r|l}
\hline
sepal\_length & sepal\_width & petal\_length & petal\_width & species\\
\hline
5.1 & 3.5 & 1.4 & 0.2 & setosa\\
\hline
4.9 & 3.0 & 1.4 & 0.2 & setosa\\
\hline
4.7 & 3.2 & 1.3 & 0.2 & setosa\\
\hline
4.6 & 3.1 & 1.5 & 0.2 & setosa\\
\hline
5.0 & 3.6 & 1.4 & 0.2 & setosa\\
\hline
5.4 & 3.9 & 1.7 & 0.4 & setosa\\
\hline
\end{tabular}

}

\end{table}%

This function (make\_clean\_names) converts all the names to lower case,
and changes to underscore instead of dots in the column names. It also
makes some more changes like writing ``percent'' instead of the
percentage symbol (\%) in the column name (if any column name has it),
etc.

\section{Finding Missing Values}\label{finding-missing-values}

Often, the data will have blank or missing values. It is easy to find
out if your data has missing values, using the \texttt{summary}
function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dummy\_data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{A =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{),}\AttributeTok{B =} \FunctionTok{c}\NormalTok{(}\DecValTok{6}\SpecialCharTok{:}\DecValTok{8}\NormalTok{,}\ConstantTok{NA}\NormalTok{,}\ConstantTok{NA}\NormalTok{))}
\FunctionTok{summary}\NormalTok{(dummy\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
       A           B      
 Min.   :1   Min.   :6.0  
 1st Qu.:2   1st Qu.:6.5  
 Median :3   Median :7.0  
 Mean   :3   Mean   :7.0  
 3rd Qu.:4   3rd Qu.:7.5  
 Max.   :5   Max.   :8.0  
             NA's   :2    
\end{verbatim}

In the code above, we created a dummy data, in which column B contains
two \texttt{NA} values. When we take \texttt{summary(dummy\_data)}, it
will show that there are two \texttt{NA}s in the data. Thus, if your
data has \texttt{NA}s, the \texttt{summary} will show it easily.
Therefore, it is a good practice to look at the summary of the data as
soon as you import it.

Summary is a powerful function in R. It will change the output depending
on the input you write in the brackets. Even if the input is a dataset,
it will change the output depending upon the types of the data in the
columns of the data. In the previous example, we saw that the output
showed items like minimum, maximum, median, mean and NA values. If we
had only text values in a column, we could see different output.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data.frame}\NormalTok{(}\FunctionTok{summary}\NormalTok{(iris}\SpecialCharTok{$}\NormalTok{Species)) }\SpecialCharTok{|\textgreater{}} \FunctionTok{kbl}\NormalTok{(}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tbl-iris-summary}Summary of `Species' column of `iris'
dataset}

\centering{

\begin{tabular}[t]{l|r}
\hline
  & summary.iris.Species.\\
\hline
setosa & 50\\
\hline
versicolor & 50\\
\hline
virginica & 50\\
\hline
\end{tabular}

}

\end{table}%

In the code above, we took summary of the \texttt{Species} column of the
\texttt{iris} dataset, which comes in-built in R. This column has only
text data in it. So, it shows the frequency of each values (setosa,
versicolor and virginica).

\section{Date Stored as Numbers}\label{date-stored-as-numbers}

Microsoft Excel is a popular spreadsheet program. So, you might have to
import data from Microsoft Excel file format quite often. However,
Microsoft Excel stores date as numbers internally. Therefore, when you
open the Microsoft Excel file, on the screen you might see a column as
date, but when you import the data in other program (like R), it would
be imported as a serial number. In such cases, the
\texttt{excel\_numeric\_to\_date} function from the \texttt{janitor}
package comes handy.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{janitor}\SpecialCharTok{::}\FunctionTok{excel\_numeric\_to\_date}\NormalTok{(}\DecValTok{45450}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "2024-06-07"
\end{verbatim}

The code above converts the numeric value 45450 to a date format. By
default, Microsoft Excel follows 1900 date system, which means 1st
January, 1900 is set as the base date, with the value of 0. All other
dates are difference of that date from the base date. The date
7-June-2024 is 45450 days away from the base date, therefore the value
of this date is 45450. The function \texttt{excel\_numeric\_to\_date}
identifies this and converts this numeric value to Date format.

\section{Identifying Outliers in
Data}\label{identifying-outliers-in-data}

\bookmarksetup{startatroot}

\chapter{Conclusion}\label{conclusion}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 0\tabcolsep) * \real{1.0000}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Status
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
This chapter is currently a dumping ground for ideas, and we don't
recommend reading it. \\
\end{longtable}

\begin{objectives}{In this chapter, you will learn to}
\begin{itemize}

\item{Summary of the key concepts covered in the book}

\item{Importance of regression analysis in econometrics and economic research}

\item{Encouragement for further exploration and application of econometric regression using R}

\end{itemize}

\end{objectives}

\begin{itemize}
\item
  Summary of the key concepts covered in the book
\item
  Importance of regression analysis in econometrics and economic
  research
\item
  Encouragement for further exploration and application of econometric
  regression using R
\end{itemize}

\cleardoublepage
\phantomsection
\addcontentsline{toc}{part}{Appendices}
\appendix

\chapter{R packages for econometric regression analysis and additional
resources}\label{r-packages-for-econometric-regression-analysis-and-additional-resources}

\setcounter{figure}{0} 
\renewcommand{\thefigure}{A.\arabic{figure}}
\setcounter{table}{0} 
\renewcommand{\thetable}{A.\arabic{table}}

This book could never be completed without using many packages. The most
notable of the packages include tidyverse, easystats, AER, lmtest, fpp3,
gujarati5sie, etc. These packages can be installed using the following
commands in R.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{RA\_packages }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"AER"}\NormalTok{,}
                 \StringTok{"easystats"}\NormalTok{,}
                 \StringTok{"fpp3"}\NormalTok{,}
                 \StringTok{"lmtest"}\NormalTok{,}
                 \StringTok{"ggthemes"}\NormalTok{,}
                 \StringTok{"gt"}\NormalTok{,}
                 \StringTok{"gtsummary"}\NormalTok{,}
                 \StringTok{"patchwork"}\NormalTok{,}
                 \StringTok{"here"}\NormalTok{,}\StringTok{"fs"}\NormalTok{,}
                 \StringTok{"knitr"}\NormalTok{,}
                 \StringTok{"kableExtra"}\NormalTok{)}
\FunctionTok{install.packages}\NormalTok{(RA\_packages)}
\end{Highlighting}
\end{Shaded}

The commands above install the packages into your R system. However, the
functionality of these packages are not added into your R session just
because you installed these packages. You have to load the required
packages specifically whenever you need them.

Imagine you are building a home. You have completed electrification in
your home. But just because you have a fan or an AC in your home doesn't
mean they start automatically. You have to switch on the appliance
whenever you need it. Similarly, you will have to load the R packages
into your session whenever you need those packages. You can load the
package using the \texttt{library(package\_name)} command. For example,
the command to load \texttt{easystats} set of packages would be

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(easystats)}
\end{Highlighting}
\end{Shaded}

When you run the \texttt{install.packages(package\_name)} command, R
installs the package from Comprehensive R Archive Network (CRAN), which
is the highest authority to decide about R. However, there are many
packages, which are not available on CRAN. These packages can be
downloaded from code sharing platform Github.

To install packages from Github, you need to install one of the three
packages first: \texttt{remotes}, \texttt{devtools} or \texttt{pak}.
After that, you can easily install packages from Github also. Apart from
such packages, the development versions of regular packages (which are
available on CRAN) can also be downloaded from Github. For example, if
you want to install the package ``gujarati5sie'', which is a package
containing data from the 5th edition of the book ``Basic Econometrics''
written by Damodar Gujarati and others, then you can do it as follows:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Install devtools, remotes or pak}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"remotes"}\NormalTok{)}\CommentTok{\#or install.packages("devltools")}
\CommentTok{\#or install.packages("pak")}
\CommentTok{\#Load the package}
\FunctionTok{library}\NormalTok{(remotes)}\CommentTok{\#or library(devtools) }
\CommentTok{\#or library(pak)}
\CommentTok{\#download the gujarati5sie package }
\CommentTok{\#using one of the above packages}
\NormalTok{remotes}\SpecialCharTok{::}\FunctionTok{install\_github}\NormalTok{(}\StringTok{"bhattmaulik/Gujarati5sie"}\NormalTok{)}
\CommentTok{\#or devtools::install\_github("bhattmaulik/Gujarati5sie") }
\CommentTok{\#or pak::pak("bhattmaulik/Gujarati5sie")}
\end{Highlighting}
\end{Shaded}

\chapter{Data sets used in the book's
examples}\label{data-sets-used-in-the-books-examples}

\setcounter{figure}{0}
\renewcommand{\thefigure}{B.\arabic{figure}} 
\setcounter{table}{0}
\renewcommand{\thetable}{B.\arabic{table}}

\subsection{Introduction}\label{introduction-3}

Dummy text

\chapter{How to Build This Book
Locally}\label{how-to-build-this-book-locally}

\setcounter{figure}{0}
\renewcommand{\thefigure}{C.\arabic{figure}}
\setcounter{table}{0}
\renewcommand{\thetable}{C.\arabic{table}}

\subsection{Introduction}\label{introduction-4}

If you want to build this book locally on your computer, please download
the entire code from Github. The first step is to visit the website
\texttt{www.github.com/bhattmaulik/RegressionAnalysis}. Here, you will
find the option to download the entire book in a zip file, as shown
below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{include\_graphics}\NormalTok{(here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"images"}\NormalTok{,}\StringTok{"download{-}book.png"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}[h]

\centering{

\includegraphics[width=4.43in,height=\textheight]{images/download-book.png}

}

\caption{\label{fig-download-book}Download the book from Github}

\end{figure}%

After you download the zip file, unzip it. This will create a folder in
your computer. Within this folder, double click on the
``RegressionAnalysis.Rproj'' file. This will open the whole project in
RStudio.

After opening this project, go to ``Build'' pane in RStudio. This pane
is generally on the top right of RStudio along with Environment,
History, Connections, Git and Tutorial. In the build pane, click on
``\texttt{Render\ Book}'' and select ``\texttt{HTML\ format}''.

You can also choose to build the book in PDF format, but for that you
will need additional software called \texttt{tinytex}. In order to build
a book in PDF format, R also needs \texttt{LaTeX} compiler. There are
two popular \texttt{LaTeX} compilers: TeX Live and MikTeX. However, they
have their own set of problems for R users. The \texttt{LaTeX} compiler
\texttt{tinytex} attempts to solve many of them.

If you want to build the PDF book, you can install \texttt{tinytex}
through terminal in RStudio using the command
\texttt{quarto\ install\ tinytex}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{include\_graphics}\NormalTok{(here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"images"}\NormalTok{,}\StringTok{"build{-}book.png"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}[h]

\centering{

\includegraphics[width=2.73in,height=\textheight]{images/build-book.png}

}

\caption{\label{fig-build-book}Build book using tinytex}

\end{figure}%

If you can't install it this way, or if you want to install it through
traditional way using R code, you can use the following code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"tinytex"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(tinytex)}
\NormalTok{tinytex}\SpecialCharTok{::}\FunctionTok{install\_tinytex}\NormalTok{()}
\CommentTok{\#if you want to install all the LaTeX packages, }
\CommentTok{\#you can modify the command to }
\CommentTok{\#tinytex::install\_tinytex(bundle = "TinyTeX{-}2")}
\end{Highlighting}
\end{Shaded}

This confuses some readers because there are two \texttt{tinytex} in
this code: the first tinytex is the \texttt{tinytex} R package. The
other \texttt{tinytex} is the \texttt{LaTeX} compiler \texttt{tinytex}.
So, when we write \texttt{library(tinytex)}, we are calling the R
package tinytex. And when we use the command \texttt{install\_tinytex},
we are installing the \texttt{LaTeX} compiler \texttt{tinytex} using the
R package \texttt{tinytex}. The benefit of this approach is that you get
to select which bundle you want to install. By default, you get to
install the bundle \texttt{TinyTeX-1}, which contains only the most
necessary LaTeX packages. But if you choose the bundle
\texttt{TinyTeX-2}, you can download all the \texttt{LaTeX} packages.

\chapter*{References}\label{references}
\addcontentsline{toc}{chapter}{References}

\markboth{References}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-ggthemes}
Arnold, Jeffrey B. 2021. \emph{{ggthemes}: Extra Themes, Scales and
Geoms for {``{ggplot2}''}}.
\url{https://CRAN.R-project.org/package=ggthemes}.

\bibitem[\citeproctext]{ref-fs}
Hester, Jim, Hadley Wickham, and Gábor Csárdi. 2023. \emph{{fs}:
Cross-Platform File System Operations Based on {``{libuv}''}}.
\url{https://CRAN.R-project.org/package=fs}.

\bibitem[\citeproctext]{ref-fpp3}
Hyndman, Rob. 2023. \emph{Fpp3: Data for {``{Forecasting: Principles and
Practice}''} (3rd Edition)}.
\url{https://CRAN.R-project.org/package=fpp3}.

\bibitem[\citeproctext]{ref-gt}
Iannone, Richard, Joe Cheng, Barret Schloerke, Ellis Hughes, Alexandra
Lauer, and JooYoung Seo. 2023. \emph{{gt}: Easily Create
Presentation-Ready Display Tables}.
\url{https://CRAN.R-project.org/package=gt}.

\bibitem[\citeproctext]{ref-AER}
Kleiber, Christian, and Achim Zeileis. 2008. \emph{Applied Econometrics
with {R}}. New York: Springer-Verlag.
\url{https://CRAN.R-project.org/package=AER}.

\bibitem[\citeproctext]{ref-easystats}
Lüdecke, Daniel, Mattan S. Ben-Shachar, Indrajeet Patil, Brenton M.
Wiernik, Etienne Bacher, Rémi Thériault, and Dominique Makowski. 2022.
{``{easystats}: Framework for Easy Statistical Modeling, Visualization,
and Reporting.''} \emph{CRAN}.
\url{https://easystats.github.io/easystats/}.

\bibitem[\citeproctext]{ref-here}
Müller, Kirill. 2020. \emph{{here}: A Simpler Way to Find Your Files}.
\url{https://CRAN.R-project.org/package=here}.

\bibitem[\citeproctext]{ref-patchwork}
Pedersen, Thomas Lin. 2022. \emph{{patchwork}: The Composer of Plots}.
\url{https://CRAN.R-project.org/package=patchwork}.

\bibitem[\citeproctext]{ref-gtsummary}
Sjoberg, Daniel D., Karissa Whiting, Michael Curry, Jessica A. Lavery,
and Joseph Larmarange. 2021. {``Reproducible Summary Tables with the
Gtsummary Package.''} \emph{{The R Journal}} 13: 570--80.
\url{https://doi.org/10.32614/RJ-2021-053}.

\bibitem[\citeproctext]{ref-knitr2014}
Xie, Yihui. 2014. {``{knitr}: A Comprehensive Tool for Reproducible
Research in {R}.''} In \emph{Implementing Reproducible Computational
Research}, edited by Victoria Stodden, Friedrich Leisch, and Roger D.
Peng. Chapman; Hall/CRC.

\bibitem[\citeproctext]{ref-knitr2015}
---------. 2015. \emph{Dynamic Documents with {R} and Knitr}. 2nd ed.
Boca Raton, Florida: Chapman; Hall/CRC. \url{https://yihui.org/knitr/}.

\bibitem[\citeproctext]{ref-knitr2023}
---------. 2023. \emph{{knitr}: A General-Purpose Package for Dynamic
Report Generation in r}. \url{https://yihui.org/knitr/}.

\bibitem[\citeproctext]{ref-lmtest}
Zeileis, Achim, and Torsten Hothorn. 2002. {``Diagnostic Checking in
Regression Relationships.''} \emph{R News} 2 (3): 7--10.
\url{https://CRAN.R-project.org/doc/Rnews/}.

\bibitem[\citeproctext]{ref-kableExtra}
Zhu, Hao. 2021. \emph{{kableExtra}: Construct Complex Table with
{``{kable}''} and Pipe Syntax}.
\url{https://CRAN.R-project.org/package=kableExtra}.

\end{CSLReferences}


\backmatter

\end{document}
